### ISSUE TITLE
Update website statistics

### ISSUE THREAD

**Issue by jos3s** [jolupa/stdbgames#10]
![Screenshot_20200810-231830_Chrome](https://user-images.githubusercontent.com/50359547/89850566-02974480-db61-11ea-9cb3-dfe485cc51f1.jpg)
It would be interesting to allow users to click on these statistics data and be taken to the page of games launched, games waiting for release.
In addition to this usability improvement, it would be interesting for the statistics to have their own page with an annual or monthly chart showing the number of games released on Stadia, the number of available Pro games and several other charts such as the number of new games announced, one graph of Stadia's Reddit growth and other information you find interesting to add

**Comment by jolupa** [comment]
This is interesting, but I'm alone building the web and the statistics page could take a little longer, I implemented the usability links on the stats navbar and will work on the statistics page.
Thanks!
