### ISSUE TITLE
Idea: Add a chart to demonstrate the price variation

### ISSUE THREAD

**Issue by jos3s** [jolupa/stdbgames#8]
It would be better for viewing if the price history could be viewed as a line graph

**Comment by jolupa** [comment]
Is a good idea and I try at the beginning to use (I think it was chart.js) but my null JavaScript compression makes a little difficult to integrate the chart and scroll it when we have a lot of entries with prices.
But I can look at it, there's no problem... Also if you can help with this could be great! 😀

**Comment by jos3s** [comment]
I would love to help, but I will not be of much help, my knowledge with web development is totally basic and would not help much. But it’s good that you want to try to make the graphics again

**Comment by jolupa** [comment]
Added chart deals on last commit a939aa409ee9398a5a4832be9cf061d848124c30
Now I'm open to make some tweaks if it's possible.
