### ISSUE TITLE
Clickable tags

### ISSUE THREAD

**Issue by jos3s** [jolupa/stdbgames#9]
![Screenshot_20200810-232141_Chrome](https://user-images.githubusercontent.com/50359547/89850375-9fa5ad80-db60-11ea-9a84-9f2da9864083.jpg)
Several games already have these tags like "Fist On Stadia", "Early Acess Game" and "Free for Pro Now!", Why not allow users to filter games based on these tags?

**Comment by jolupa** [comment]
Added the option in the new commit!

**Comment by jos3s** [comment]
Any news about filtering games by tags? For example games the tag "Free for Pro now!" should take to the page that shows all the pro games

**Comment by jolupa** [comment]
> Any news about filtering games by tags? For example games the tag "Free for Pro now!" should take to the page that shows all the pro games

Yeah it is added every game that is early, first or exclusive tag is pointing to the list with that games. :smile:
